name: Complete Project Pipeline


on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build -t ainalsagr/complete-project:${{ env.SHORT_SHA }} .
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker image
        run: docker push ainalsagr/complete-project:${{ env.SHORT_SHA }}
